/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import java.util.Collection;
import model.Agente;

/**
 *
 * @author W10-Portable
 */
public class CreateOperacionDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateOperacionDialog.class.getName());

    /**
     * Creates new form CreateOperacionDialog
     */
    public CreateOperacionDialog(java.awt.Frame parent, boolean modal, Collection<Agente> agentes) {
        super(parent, modal);
        initComponents();
        insertSaveAgentsInComboBox(agentes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        agenteLabel = new javax.swing.JLabel();
        typeOperacionLabel = new javax.swing.JLabel();
        agenteComboBox = new javax.swing.JComboBox<>();
        typeOperacionComboBox = new javax.swing.JComboBox<>();
        limiteLabel = new javax.swing.JLabel();
        cantidadLabel = new javax.swing.JLabel();
        cantidadSpinner = new javax.swing.JSpinner();
        limiteTextField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titleLabel.setText("Crear Operacion:");

        agenteLabel.setText("Agente:");

        typeOperacionLabel.setText("Tipo de Op:");

        typeOperacionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "compra", "venta" }));

        limiteLabel.setText("Precio:");

        cantidadLabel.setText("Cantidad:");

        cantidadSpinner.setValue(1);

        createButton.setText("Crear");

        cancelButton.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleLabel)
                                .addGap(118, 118, 118))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeOperacionLabel)
                                    .addComponent(agenteLabel)
                                    .addComponent(limiteLabel)
                                    .addComponent(cantidadLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cantidadSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(limiteTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(typeOperacionComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 90, Short.MAX_VALUE))
                                        .addGap(0, 178, Short.MAX_VALUE))
                                    .addComponent(agenteComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agenteLabel)
                    .addComponent(agenteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeOperacionLabel)
                    .addComponent(typeOperacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limiteLabel)
                    .addComponent(limiteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadLabel)
                    .addComponent(cantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(createButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setCreateButtonActionListener(ActionListener al){
        this.createButton.addActionListener(al);
    }
    
    public void setCancelButtonActionListener(ActionListener al){
        this.cancelButton.addActionListener(al);
    }
    
    public int getIndexAgenteComboBox(){
        return this.agenteComboBox.getSelectedIndex();
    }
    
    public Agente getSelectAgenteComboBox(){
        return this.agenteComboBox.getItemAt(this.getIndexAgenteComboBox());
    }
    
    public int getIndexTypeOperacionComboBox(){
        return this.typeOperacionComboBox.getSelectedIndex();
    }
    
    public String getSelectTypeOperacionComboBox(){
        return this.typeOperacionComboBox.getItemAt(this.getIndexTypeOperacionComboBox());
    }
    
    public String getTextLimiteTextField(){
        return this.limiteTextField.getText();
    }
    
    public double getDoubleLimiteAgenteTextField(){
        double limite = 0;
        try {
            limite = Double.parseDouble(this.getTextLimiteTextField());
        } catch(NumberFormatException ex){
            System.err.println(ex.getMessage());
        }
        
        return limite;
    }
    
    public int getCantidadSpinner(){
        return (Integer) this.cantidadSpinner.getValue();
    }
    
    private void insertSaveAgentsInComboBox(Collection<Agente> agentes){
        for(Agente agente : agentes){
            this.agenteComboBox.addItem(agente);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Agente> agenteComboBox;
    private javax.swing.JLabel agenteLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JSpinner cantidadSpinner;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel limiteLabel;
    private javax.swing.JTextField limiteTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<String> typeOperacionComboBox;
    private javax.swing.JLabel typeOperacionLabel;
    // End of variables declaration//GEN-END:variables
}
