/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;

/**
 *
 * @author dam2_alu13@inf.ald
 */
public class MainJFrame extends javax.swing.JFrame {
    DefaultListModel<String> demoList = new DefaultListModel<>();
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsTabbed = new javax.swing.JTabbedPane();
        bolsaPanel = new javax.swing.JPanel();
        gestorAgentePanel = new javax.swing.JPanel();
        createAgentButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deleteAgentButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        agentsList = new javax.swing.JList<>();
        gestorOperacionPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout bolsaPanelLayout = new javax.swing.GroupLayout(bolsaPanel);
        bolsaPanel.setLayout(bolsaPanelLayout);
        bolsaPanelLayout.setHorizontalGroup(
            bolsaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        bolsaPanelLayout.setVerticalGroup(
            bolsaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        panelsTabbed.addTab("Bolsa", bolsaPanel);

        createAgentButton.setText("Crear");

        jLabel1.setText("Agentes:");

        deleteAgentButton.setText("Eliminar");

        agentsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(agentsList);

        javax.swing.GroupLayout gestorAgentePanelLayout = new javax.swing.GroupLayout(gestorAgentePanel);
        gestorAgentePanel.setLayout(gestorAgentePanelLayout);
        gestorAgentePanelLayout.setHorizontalGroup(
            gestorAgentePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gestorAgentePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gestorAgentePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gestorAgentePanelLayout.createSequentialGroup()
                        .addGap(0, 305, Short.MAX_VALUE)
                        .addComponent(deleteAgentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createAgentButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gestorAgentePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gestorAgentePanelLayout.setVerticalGroup(
            gestorAgentePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gestorAgentePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(gestorAgentePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createAgentButton)
                    .addComponent(deleteAgentButton))
                .addContainerGap())
        );

        panelsTabbed.addTab("Agentes", gestorAgentePanel);

        javax.swing.GroupLayout gestorOperacionPanelLayout = new javax.swing.GroupLayout(gestorOperacionPanel);
        gestorOperacionPanel.setLayout(gestorOperacionPanelLayout);
        gestorOperacionPanelLayout.setHorizontalGroup(
            gestorOperacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        gestorOperacionPanelLayout.setVerticalGroup(
            gestorOperacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        panelsTabbed.addTab("Operaciones", gestorOperacionPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelsTabbed, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelsTabbed)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setCreateAgentActionListener(ActionListener al){
        this.createAgentButton.addActionListener(al);
    }
    
    public void setDeleteAgentActionListener(ActionListener al){
        this.deleteAgentButton.addActionListener(al);
    }
    
    public int getIndexItemList(){
        return this.agentsList.getSelectedIndex();
    }
    
    public void delItemList(int index){
        this.demoList.remove(index);
    }
    
    public void addAgent(String agente){
        demoList.addElement(agente);
        agentsList.setModel(demoList);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> agentsList;
    private javax.swing.JPanel bolsaPanel;
    private javax.swing.JButton createAgentButton;
    private javax.swing.JButton deleteAgentButton;
    private javax.swing.JPanel gestorAgentePanel;
    private javax.swing.JPanel gestorOperacionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane panelsTabbed;
    // End of variables declaration//GEN-END:variables

}
